
version: "3.6"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres.arent.healthyapp
    command: postgres -c max_connections=200
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      ENV: ${ENV:-develop}
    volumes:
      - ./config/postgresql/data:/var/lib/postgresql/data
      - ./config/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  migrate:
    build:
      context: packages/migrate
      dockerfile: Dockerfile
    container_name:  migrate.arent.healthyapp
    volumes:
      - ./packages/migrate:/packages/migrate
  
  api:
    build: 
      context: packages/api/healthyapp
      dockerfile: Dockerfile
    ports:
      - "8176:8176"
    container_name: api.arent.healthyapp
    volumes:
      - ./packages/api/healthyapp:/app/packages/api/healthyapp