// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package dbmodels

import (
	"database/sql"
	"time"
)

type Diary struct {
	ID        int32     `json:"ID"`
	Content   string    `json:"content"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Exercise struct {
	ID        int32     `json:"ID"`
	Type      int16     `json:"type"`
	Rate      float64   `json:"rate"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ExerciseHistory struct {
	Date           time.Time `json:"date"`
	UserID         int32     `json:"user_id"`
	ExerciseID     int32     `json:"exercise_id"`
	CaloriesBurned int32     `json:"calories_burned"`
	Timer          int32     `json:"timer"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type MealHistory struct {
	ID        int32     `json:"ID"`
	Date      time.Time `json:"date"`
	Session   int16     `json:"session"`
	UserID    int32     `json:"user_id"`
	ImageUrl  string    `json:"image_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type News struct {
	ID         int32     `json:"ID"`
	Title      string    `json:"title"`
	ImageUrl   string    `json:"image_url"`
	Content    string    `json:"content"`
	CategoryID int32     `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type NewsCategory struct {
	ID        int32     `json:"ID"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NewsTag struct {
	NewsID int32 `json:"news_id"`
	TagID  int32 `json:"tag_id"`
}

type Tag struct {
	ID   int32  `json:"ID"`
	Name string `json:"name"`
}

type User struct {
	ID            int32        `json:"ID"`
	FirstName     string       `json:"first_name"`
	LastName      string       `json:"last_name"`
	Email         string       `json:"email"`
	Birthday      time.Time    `json:"birthday"`
	CurrentWeight float64      `json:"current_weight"`
	GoalWeight    float64      `json:"goal_weight"`
	Height        float64      `json:"height"`
	Gender        sql.NullBool `json:"gender"`
	Password      string       `json:"password"`
}
