// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package dbmodels

import (
	"context"
)

type Querier interface {
	CreateDiary(ctx context.Context, arg CreateDiaryParams) (Diary, error)
	GetExercseHistoryByDate(ctx context.Context, arg GetExercseHistoryByDateParams) ([]GetExercseHistoryByDateRow, error)
	GetExercseHistoryOfUser(ctx context.Context, arg GetExercseHistoryOfUserParams) ([]GetExercseHistoryOfUserRow, error)
	GetMealHistory(ctx context.Context, arg GetMealHistoryParams) ([]MealHistory, error)
	GetMealHistoryBySession(ctx context.Context, arg GetMealHistoryBySessionParams) ([]MealHistory, error)
	GetUserDiary(ctx context.Context, arg GetUserDiaryParams) ([]GetUserDiaryRow, error)
	ListNews(ctx context.Context, arg ListNewsParams) ([]ListNewsRow, error)
	LoginAccount(ctx context.Context, arg LoginAccountParams) (LoginAccountRow, error)
}

var _ Querier = (*Queries)(nil)
