// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: User.sql

package dbmodels

import (
	"context"
)

const loginAccount = `-- name: LoginAccount :one
SELECT u."ID", u.first_name, u.last_name, u.email, u.password 
FROM public."User" as u
Where u.email = $1 AND u.password = $2
`

type LoginAccountParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginAccountRow struct {
	ID        int32  `json:"ID"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

func (q *Queries) LoginAccount(ctx context.Context, arg LoginAccountParams) (LoginAccountRow, error) {
	row := q.db.QueryRowContext(ctx, loginAccount, arg.Email, arg.Password)
	var i LoginAccountRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
	)
	return i, err
}
