CREATE TABLE "User" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" VARCHAR(100) NOT NULL,
  "last_name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(50) NOT NULL,
  "birthday" datetime NOT NULL,
  "current_weight" DOUBLE NOT NULL,
  "current_goal" SMALLINT NOT NULL,
  "goal_weight" DOUBLE NOT NULL,
  "height" DOUBLE NOT NULL,
  "gender" SMALLINT NOT NULL,
  "password" VARCHAR(255) NOT NULL
);

CREATE TABLE "Diary" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" longtext,
  "user_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "Exercise" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" SMALLINT NOT NULL,
  "rate" DOUBLE NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "Exercise_History" (
  "date" timestamptz NOT NULL,
  "user_id" integer NOT NULL,
  "exercise_id" integer NOT NULL,
  "calories_burned" integer NOT NULL,
  "timer" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "News_Category" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "Tag" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "News" (
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "image_url" VARCHAR(255),
  "content" longtext NOT NULL,
  "category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "News_Tag" (
  "news_id" integer NOT NULL,
  "tag_id" integer NOT NULL
);

CREATE INDEX ON "Exercise_History" ("user_id");

CREATE INDEX ON "Exercise_History" ("exercise_id");

CREATE INDEX ON "Exercise_History" ("user_id", "exercise_id");

CREATE INDEX ON "News_Tag" ("news_id");

CREATE INDEX ON "News_Tag" ("tag_id");

CREATE INDEX ON "News_Tag" ("news_id", "tag_id");

ALTER TABLE "Diary" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("ID");

ALTER TABLE "Exercise_History" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("ID");

ALTER TABLE "Exercise_History" ADD FOREIGN KEY ("exercise_id") REFERENCES "Exercise" ("ID");

ALTER TABLE "News" ADD FOREIGN KEY ("category_id") REFERENCES "News_Category" ("ID");

ALTER TABLE "News_Tag" ADD FOREIGN KEY ("news_id") REFERENCES "News" ("ID");

ALTER TABLE "News_Tag" ADD FOREIGN KEY ("tag_id") REFERENCES "Tag" ("ID");
